import { addDays } from "./dates";
import { LIMITS } from "./types";

// Demo visibility (MVP_SPEC §7). Unsent demos (expires_at null) are never
// public; the admin previews them from the admin screen.

export type DemoVisibility = { expiresAt: Date | null; disabledAt: Date | null; keepAlive: boolean };

export function isDemoPublic(demo: DemoVisibility, now: Date): boolean {
  if (demo.disabledAt !== null) return false;
  if (demo.expiresAt === null) return false;
  return demo.keepAlive || now.getTime() < demo.expiresAt.getTime();
}

export function demoExpiryFromSent(sentAt: Date): Date {
  return addDays(sentAt, LIMITS.demoDaysAfterSent);
}

/** 256-bit URL-safe token check (tokens are generated by the database). */
export function isWellFormedDemoToken(token: string): boolean {
  return /^[A-Za-z0-9_-]{43,128}$/.test(token);
}
